<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'rgb (artistic set)' => $set . '_f100',
	'pantone (artistic set)' => $set . '_f101',
	'paint-brush (artistic set)' => $set . '_f102',
	'highlighter (artistic set)' => $set . '_f103',
	'canvas (artistic set)' => $set . '_f104',
	'watercolor (artistic set)' => $set . '_f105',
	'camera-roll (artistic set)' => $set . '_f106',
	'scissors (artistic set)' => $set . '_f107',
	'eye (artistic set)' => $set . '_f108',
	'paint-roller (artistic set)' => $set . '_f109',
	'cd (artistic set)' => $set . '_f10a',
	'protractor (artistic set)' => $set . '_f10b',
	'pipette (artistic set)' => $set . '_f10c',
	'pencil-case (artistic set)' => $set . '_f10d',
	'art-book (artistic set)' => $set . '_f10e',
	'fountain-pen (artistic set)' => $set . '_f10f',
	'stapler-remover (artistic set)' => $set . '_f110',
	'pencil-box (artistic set)' => $set . '_f111',
	'frames (artistic set)' => $set . '_f112',
	'paint-palette (artistic set)' => $set . '_f113',
	'piano (artistic set)' => $set . '_f114',
	'eraser (artistic set)' => $set . '_f115',
	'theater-masks (artistic set)' => $set . '_f116',
	'vase (artistic set)' => $set . '_f117',
	'drawing-tablet (artistic set)' => $set . '_f118',
	'painter (artistic set)' => $set . '_f119',
	'pencil (artistic set)' => $set . '_f11a',
	'tea-cup (artistic set)' => $set . '_f11b',
	'harp (artistic set)' => $set . '_f11c',
	'ink (artistic set)' => $set . '_f11d',
	'director-chair (artistic set)' => $set . '_f11e',
	'column (artistic set)' => $set . '_f11f',
	'sharpener (artistic set)' => $set . '_f120',
	'video-camera (artistic set)' => $set . '_f121',
	'oil-paint (artistic set)' => $set . '_f122',
	'paper-roll (artistic set)' => $set . '_f123',
	'spotlight (artistic set)' => $set . '_f124',
	'origami (artistic set)' => $set . '_f125',
	'paint-scraper (artistic set)' => $set . '_f126',
	'printer (artistic set)' => $set . '_f127',
	'computer (artistic set)' => $set . '_f128',
	'cutter (artistic set)' => $set . '_f129',
	'3d (artistic set)' => $set . '_f12a',
	'mouse (artistic set)' => $set . '_f12b',
	'hand (artistic set)' => $set . '_f12c',
	'sketchbook (artistic set)' => $set . '_f12d',
	'paint-bucket (artistic set)' => $set . '_f12e',
	'spray (artistic set)' => $set . '_f12f',
	'photo-camera (artistic set)' => $set . '_f130',
	'paint-brush-1 (artistic set)' => $set . '_f131'
);