<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'theatre (arts set)' => $set . '_f100',
	'no-phone (arts set)' => $set . '_f101',
	'lighter (arts set)' => $set . '_f102',
	'ticket (arts set)' => $set . '_f103',
	'painting (arts set)' => $set . '_f104',
	'video-camera (arts set)' => $set . '_f105',
	'mask (arts set)' => $set . '_f106',
	'harp (arts set)' => $set . '_f107',
	'spotlight (arts set)' => $set . '_f108',
	'mixer (arts set)' => $set . '_f109',
	'3d-glasses (arts set)' => $set . '_f10a',
	'amplifier (arts set)' => $set . '_f10b',
	'clap (arts set)' => $set . '_f10c',
	'movie-camera (arts set)' => $set . '_f10d',
	'lyre (arts set)' => $set . '_f10e',
	'microphone (arts set)' => $set . '_f10f',
	'moustache (arts set)' => $set . '_f110',
	'guitar (arts set)' => $set . '_f111',
	'sound-system (arts set)' => $set . '_f112',
	'dress (arts set)' => $set . '_f113',
	'red-carpet (arts set)' => $set . '_f114',
	'sound-system-1 (arts set)' => $set . '_f115',
	'camera (arts set)' => $set . '_f116',
	'hat (arts set)' => $set . '_f117',
	'papyrus (arts set)' => $set . '_f118',
	'super-8 (arts set)' => $set . '_f119',
	'placeholder (arts set)' => $set . '_f11a',
	'bouquet (arts set)' => $set . '_f11b',
	'bass (arts set)' => $set . '_f11c',
	'film-roll (arts set)' => $set . '_f11d',
	'mask-1 (arts set)' => $set . '_f11e',
	'magic-hat (arts set)' => $set . '_f11f',
	'disco-ball (arts set)' => $set . '_f120',
	'keyboard (arts set)' => $set . '_f121',
	'audience (arts set)' => $set . '_f122',
	'no-camera (arts set)' => $set . '_f123',
	'microphone-1 (arts set)' => $set . '_f124',
	'invitation (arts set)' => $set . '_f125',
	'theatre-1 (arts set)' => $set . '_f126',
	'note (arts set)' => $set . '_f127',
	'high-heels (arts set)' => $set . '_f128',
	'drum (arts set)' => $set . '_f129',
	'clipboard (arts set)' => $set . '_f12a',
	'cinema-projector (arts set)' => $set . '_f12b',
	'hand (arts set)' => $set . '_f12c',
	'camera-1 (arts set)' => $set . '_f12d',
	'dj (arts set)' => $set . '_f12e',
	'stage (arts set)' => $set . '_f12f',
	'guitar-1 (arts set)' => $set . '_f130',
	'clapperboard (arts set)' => $set . '_f131'
);