<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'mask-2 (entertainment set)' => $set . '_f100',
	'concert (entertainment set)' => $set . '_f101',
	'cinema (entertainment set)' => $set . '_f102',
	'popcorn (entertainment set)' => $set . '_f103',
	'water-gun (entertainment set)' => $set . '_f104',
	'film-strip-1 (entertainment set)' => $set . '_f105',
	'sound (entertainment set)' => $set . '_f106',
	'joystick (entertainment set)' => $set . '_f107',
	'music-player (entertainment set)' => $set . '_f108',
	'projector (entertainment set)' => $set . '_f109',
	'cassete (entertainment set)' => $set . '_f10a',
	'camera-1 (entertainment set)' => $set . '_f10b',
	'ipod (entertainment set)' => $set . '_f10c',
	'sound-system (entertainment set)' => $set . '_f10d',
	'gameboy (entertainment set)' => $set . '_f10e',
	'binoculars (entertainment set)' => $set . '_f10f',
	'chair (entertainment set)' => $set . '_f110',
	'mask-1 (entertainment set)' => $set . '_f111',
	'line (entertainment set)' => $set . '_f112',
	'mirror (entertainment set)' => $set . '_f113',
	'light (entertainment set)' => $set . '_f114',
	'unicycle (entertainment set)' => $set . '_f115',
	'dice (entertainment set)' => $set . '_f116',
	'cards (entertainment set)' => $set . '_f117',
	'magic-2 (entertainment set)' => $set . '_f118',
	'star (entertainment set)' => $set . '_f119',
	'countdown (entertainment set)' => $set . '_f11a',
	'theater-1 (entertainment set)' => $set . '_f11b',
	'magic-1 (entertainment set)' => $set . '_f11c',
	'magic (entertainment set)' => $set . '_f11d',
	'music (entertainment set)' => $set . '_f11e',
	'drums (entertainment set)' => $set . '_f11f',
	'tickets (entertainment set)' => $set . '_f120',
	'buttons (entertainment set)' => $set . '_f121',
	'camera (entertainment set)' => $set . '_f122',
	'tetris (entertainment set)' => $set . '_f123',
	'puzzle (entertainment set)' => $set . '_f124',
	'film-strip (entertainment set)' => $set . '_f125',
	'video-camera (entertainment set)' => $set . '_f126',
	'3d-glasses (entertainment set)' => $set . '_f127',
	'award (entertainment set)' => $set . '_f128',
	'theater (entertainment set)' => $set . '_f129',
	'mask (entertainment set)' => $set . '_f12a',
	'piano (entertainment set)' => $set . '_f12b',
	'speaker (entertainment set)' => $set . '_f12c',
	'location (entertainment set)' => $set . '_f12d',
	'microphone (entertainment set)' => $set . '_f12e',
	'film-reel (entertainment set)' => $set . '_f12f',
	'tic-tac-toe (entertainment set)' => $set . '_f130',
	'clapboard (entertainment set)' => $set . '_f131'
);